#mi configuracion de hyprland
#//////////Project_azumanga\\\\\\\\\\


#                          -*#########%*-
#                      *###################%:
#                   =##*#####***##***#*########:
#                 -*############***#*#*##*#######.
#                ***+*+*+*****###-=####****+++++**=
#               **+**########*##--.-######*####**+++
#              =*#######*#*++##-:.-.:###.*#########+-
#              ########-##=-#*-:..=...##-.*##########
#             :#######-=#=.-+-.........##..#*+#######-
#             *#####*-.*%#*%%......-.:.*%*#%#.*#*####*
#             ######-:*+%###%......:...*####=*.#######
#             #####=:+ %#####=........=##%##% %.######
#            .#####:+.-##%%%#*........*#%%%##-+.=#####
#            .#####.:=.%#%%%#=........-%%%%#%.=.+#####.
#            .#####:...- .-*%....:.....= +**#...*#####:
#            .###*#:...:........................######:
#            :#####-...............::...........######:   ___________
#            :######.....:::...%+:.-+*.........+######:  /           \
#            =##**#%#.........*+-----+-.:..:..*%######: < SATA ANDAGI |
#            +##*##%%%#:......--------.....:+%%##*####:  \___________/
#            *###*####%#%%+-:...-==+...:-+%#%#########:
#            *####*#####%#%%%*++=---=+++%%############.
#            *###**####%%%%%.=-----=---=-*##%:###*####
#            *###**##% %%%-.:=---------+--:#-+%%#*###%
#            +####*#%%+.. .  :.:------==---:.-%%#####*
#            :######=  ......-.....:-=-=:....  %##%%%:
#             ###*##. ....... =---=*===........%##%%%
#             .#:###-.........==---===........=%#%%%=
#              -++### ... ...  =----=-... .   #%%#+%
#             .-*-+*#.=. :+:-..-----= ...++...%##-#=-
#            .=----=+*-..=+:....===-. ...=:=.+%+--+-=:
#            ===------=--=.=. ...+==.  -+:.-=#--=--=-=
#           ==--------------=:..+==+: .==-----=-------+
#          .-==---=---------=--==+##=--=---------=---==.
#          =--=---+--------------=---------------==--=-=
#         .=-----=+---------------+#-------------=+-+--=.
#         -----*-++--------------==*-------------=+=+---=
#         =----+*+=--------------+-===------------*++---=
#        .-----++*=--------------*--+------------=+++----:
#        -=----=++=--------------#--*------------=++=----=
#        -------++---------------#--*-------------++=----=
#        ==-----+*---------------*-=#-------------*+=---==.
#       .=----=-=+--------------=+--#---=---------*+=---=-.
#       .-------=+--------------==--+-------------++=-----=
#       =--------+-=------------+=--==------------++=-----=
#       =--------=--------------*=--=*-=----------++------=
#       ==-------==-==----------#=+--#------------*+-------:
#      .---------=--------------#-*+-#------------++-------=
#      =---------==---------------++--------------+=-------=
#      =--------==-------------=--++=-------------+=-------=
#      =--------=------=========--+++================-------.
#      =--------=--------------=--+++=-------------=--------=

#quiero keke

# para el monitor
source = ~/.config/hypr/conf.d/00-monitor.conf

# variables de negros
source = ~/.config/hypr/conf.d/01-variables.conf

# weas para conectar las cosas
source = ~/.config/hypr/conf.d/02-input.conf

# cosas en general
source = ~/.config/hypr/conf.d/03-general.conf

# la decoracion ai para que sea mas bonito
source = ~/.config/hypr/conf.d/04-decoration.conf

# animaciones flipantes
source = ~/.config/hypr/conf.d/05-animations.conf

# sepa la bola
source = ~/.config/hypr/conf.d/06-layout.conf

# tampoco se pero es importante
source = ~/.config/hypr/conf.d/07-bindings.conf

# reglas para las ventanas y que no se pongan negras
source = ~/.config/hypr/conf.d/08-rules.conf

# cosas para que se inicien al principio del sistema
source = ~/.config/hypr/conf.d/09-autostart.conf

# comportamientos de las ventanas
source = ~/.config/hypr/conf.d/10-env.conf
