##################################################
# Monitores
##################################################

# mi monitor cuadrado
monitor = DP-2,1024x768@60,0x0,1

# el monitor de la laptop
monitor = eDP-1,1366x768@60,1024x0,1
