##################################################
# Variables
##################################################

$mainMod = SUPER

$terminal = kitty

$fileManager = dolphin

$browser = flatpak run app.zen_browser.zen

$menu = wofi --show drun

#hola XD
