##################################################
# Configuración General
##################################################

general {

    gaps_in = 6

    gaps_out = 12

    border_size = 2

    col.active_border = rgba(6EC6FFFF)

    col.inactive_border = rgba(5A5A5AFF)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

#muy simple por ahora
