##################################################
# Configuración General
##################################################

general {

    gaps_in = 6

    gaps_out = 12

    border_size = 2

    col.active_border = rgba(f7c8d9ff) rgba(d6c7ffff) 45deg

    col.inactive_border = rgba(a2c4ecff) rgba(5c5470aa) 10deg

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

#hola, mucho gusto, bienvenido a la casa de los sustos
