##################################################
# Layouts
##################################################

dwindle {

    pseudotile = true

    preserve_split = true

    smart_split = false

    smart_resizing = true
}

master {

    new_status = master

    mfact = 0.55

}

#ni idea que sea esto pero solo puse lo que ya estaba en el archivo original XD
