##################################################
# Reglas de ventanas
##################################################
#quiero keke
#aun no pongo nada porque no lo he necesitado hasta ahora






#nada de nada :)
