#Autostart

#aplicaciones que se inicien al entrar a hyprland
exec-once = kdeconnectd
exec-once = /usr/libexec/xdg-desktop-portal-hyprland
exec-once = hyprpaper
exec-once = bash $HOME/.config/hypr/cambiar_fondo.sh
exec-once = waybar
