##################################################
# Variables de entorno
##################################################

#tampoco se para que es esto
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORM,wayland

# Wayland para Firefox/Zen
env = MOZ_ENABLE_WAYLAND,1

# Chromium y derivados
env = OZONE_PLATFORM,wayland

# Cursor
env = XCURSOR_SIZE,24
